type Grade = "A" | "B" | "C" | "D" | "F";

export type Datum = {
	firstName: string;
	lastName: string;
	bio: string;
	image: string;

	donated: number; // billions
	pledged: number;
	wealth: number; // billions

	dollarImpact: number;
	livesImpact: number;
};

export const billionaires: Datum[] = [
	{
		firstName: "Bill",
		lastName: "Gates",
		image: "./pinkcircle.png",
		dollarImpact: 34000,
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		livesImpact: 6800,
		donated: 38,
		pledged: 45,
		wealth: 127.8,
	},
	{
		firstName: "Elon",
		lastName: "Musk",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 21000,
		livesImpact: 4200,
		donated: 7.2,
		pledged: 0,
		wealth: 229.7,
	},
	{
		firstName: "Melinda",
		lastName: "Gates",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 32200,
		livesImpact: 6440,
		donated: 36,
		pledged: 3,
		wealth: 5.8,
	},
	{
		firstName: "Bernard",
		lastName: "Arnault",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 160,
		livesImpact: 32,
		donated: 3.2,
		pledged: 0,
		wealth: 155.7,
	},
	{
		firstName: "Jeff",
		lastName: "Bezos",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 4000,
		livesImpact: 800,
		donated: 12.5,
		pledged: 0,
		wealth: 145.9,
	},
	{
		firstName: "Warren",
		lastName: "Buffet",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 28700,
		livesImpact: 5740,
		donated: 32.1,
		pledged: 114,
		wealth: 114.2,
	},
	{
		firstName: "Larry",
		lastName: "Ellison",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 240,
		livesImpact: 48,
		donated: 0.7,
		pledged: 49,
		wealth: 99.2,
	},
	{
		firstName: "Gautam",
		lastName: "Adani",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 250,
		livesImpact: 50,
		donated: 0.5,
		pledged: 0,
		wealth: 99.1,
	},
	{
		firstName: "Mukesh",
		lastName: "Ambani",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 80,
		livesImpact: 16,
		donated: 0.4,
		pledged: 7,
		wealth: 98.1,
	},
	{
		firstName: "Larry",
		lastName: "Page",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 310,
		livesImpact: 62,
		donated: 2.7,
		pledged: 20,
		wealth: 98,
	},
	{
		firstName: "Sergey",
		lastName: "Brin",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 1200,
		livesImpact: 240,
		donated: 3.7,
		pledged: 5,
		wealth: 94.2,
	},
	{
		firstName: "Carlos Slim",
		lastName: "Helu",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 130,
		livesImpact: 26,
		donated: 4.2,
		pledged: 0,
		wealth: 91.5,
	},
	{
		firstName: "Steve",
		lastName: "Ballmer",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 550,
		livesImpact: 110,
		donated: 2.1,
		pledged: 0,
		wealth: 89.2,
	},
	{
		firstName: "Michael",
		lastName: "Bloomberg",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 2100,
		livesImpact: 420,
		donated: 10.3,
		pledged: 0,
		wealth: 82,
	},
	{
		firstName: "Francoise Bettencourt",
		lastName: "Meyers",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 40,
		livesImpact: 8,
		donated: 0.6,
		pledged: 0,
		wealth: 70.5,
	},
	{
		firstName: "Mark",
		lastName: "Zuckerberg",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 42,
		livesImpact: 8,
		donated: 3.1,
		pledged: 20,
		wealth: 34.7,
	},
	{
		firstName: "Priscilla",
		lastName: "Chan",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 42,
		livesImpact: 8,
		donated: 3.1,
		pledged: 20,
		wealth: 34.7,
	},
	{
		firstName: "Zhong",
		lastName: "Shanshan",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 15,
		livesImpact: 3,
		donated: 0.2,
		pledged: 0,
		wealth: 66.6,
	},
	{
		firstName: "Charles",
		lastName: "Koch",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 120,
		livesImpact: 24,
		donated: 1.3,
		pledged: 7,
		wealth: 63.6,
	},
	{
		firstName: "Julia",
		lastName: "Koch",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 42,
		livesImpact: 8,
		donated: 0.5,
		pledged: 3,
		wealth: 63.6,
	},
	{
		firstName: "Jim",
		lastName: "Walton",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 85,
		livesImpact: 17,
		donated: 1.7,
		pledged: 0,
		wealth: 61.3,
	},
	{
		firstName: "Alice",
		lastName: "Walton",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 10,
		livesImpact: 2,
		donated: 0.2,
		pledged: 0,
		wealth: 60.4,
	},
	{
		firstName: "Michael",
		lastName: "Dell",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 1100,
		livesImpact: 220,
		donated: 2.4,
		pledged: 15,
		wealth: 57.2,
	},
	{
		firstName: "Jim",
		lastName: "Simons",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 94,
		livesImpact: 19,
		donated: 2.7,
		pledged: 20,
		wealth: 29.2,
	},
	{
		firstName: "Phil",
		lastName: "Knight",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 27,
		livesImpact: 5,
		donated: 2.2,
		pledged: 0,
		wealth: 46.1,
	},
	{
		firstName: "Mackenzie",
		lastName: "Scott",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 3800,
		livesImpact: 760,
		donated: 12,
		pledged: 30,
		wealth: 35.6,
	},
	{
		firstName: "Ray",
		lastName: "Dalio",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 450,
		livesImpact: 90,
		donated: 5.2,
		pledged: 11,
		wealth: 22.4,
	},
	{
		firstName: "Sam",
		lastName: "Bankman-Fried",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 19000,
		livesImpact: 3800,
		donated: 0.3,
		pledged: 24,
		wealth: 24.8,
	},
	{
		firstName: "Jack",
		lastName: "Ma",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 17000,
		livesImpact: 3400,
		donated: 3.6,
		pledged: 12,
		wealth: 23.8,
	},
	{
		firstName: "Dustin",
		lastName: "Moskovitz",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 80000,
		livesImpact: 16000,
		donated: 0.8,
		pledged: 5.4,
		wealth: 5.5,
	},
	{
		firstName: "George",
		lastName: "Soros",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 5300,
		livesImpact: 1060,
		donated: 17,
		pledged: 7,
		wealth: 8.6,
	},
	{
		firstName: "Cari",
		lastName: "Tuna",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 80000,
		livesImpact: 16000,
		donated: 0.8,
		pledged: 5.4,
		wealth: 5.5,
	},
	{
		firstName: "Peter",
		lastName: "Thiel",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 12000,
		livesImpact: 2400,
		donated: 0.3,
		pledged: 0,
		wealth: 4.7,
	},
	{
		firstName: "Vitalik",
		lastName: "Buterin",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 34000,
		livesImpact: 6800,
		donated: 1.6,
		pledged: 0.8,
		wealth: 0.9,
	},
	{
		firstName: "Jaan",
		lastName: "Tallinn",
		bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		image: "./pinkcircle.png",
		dollarImpact: 7000,
		livesImpact: 1400,
		donated: 0.026,
		pledged: 1.1,
		wealth: 1.2,
	},
];
